In [1]:
import numpy as np
import time
import sys

In [11]:
#space-complexity

list_ = range(100000)
print(len(list_)*sys.getsizeof(5))

array_ = np.arange(100000)
print(array_.size*array_.itemsize)

2800000
400000


In [26]:
#time-complexity

SIZE = 10000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

#python-list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print('python list took: ', (time.time()-start)*1000)

#numpy-array
start = time.time()
result = a1 + a2
print('numpy array took: ', (time.time()-start)*1000)

python list took:  1203.6869525909424
numpy array took:  109.56430435180664


In [27]:
summ = np.array([1,2,3]) + np.array([4,5,6])
print(summ)

[5 7 9]


In [62]:
array = np.array([1,2,3])
array.ndim

1

In [33]:
array = np.array([[1,2],[3,4],[5,6]])
array.ndim

2

In [35]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array.ndim

3

In [59]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.itemsize)
print(array.size) #total number of element in array
print(array.shape)
print(array.dtype)

4
9
(3, 3)
int32


In [58]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype = np.float64)
print(array.itemsize)
print(array.size) #total number of element in array
print(array.shape)
print(array.dtype)

8
9
(1, 3, 3)
float64


In [63]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype = complex)
print(array)

[[[1.+0.j 2.+0.j 3.+0.j]
  [4.+0.j 5.+0.j 6.+0.j]
  [7.+0.j 8.+0.j 9.+0.j]]]


In [64]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.ones( (3,5) )

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
np.ones( (4,3) )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [70]:
np.arange(1,6,2)

array([1, 3, 5])

In [71]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [80]:
array = np.array([[1,2],[3,4],[5,6]])
array = array.reshape(2,3)
print(array.shape)
array

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
array = np.array([[1,2],[3,4],[5,6]])
array = array.reshape(1,6)
print(array.shape)
array

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [85]:
array = np.array([[1,2],[3,4],[5,6]])
array.ravel()

array([1, 2, 3, 4, 5, 6])

In [84]:
array

array([[1, 2, 3, 4, 5, 6]])

In [95]:
array = np.array([[1,2],[3,4],[5,6]])
print(array.min())
print(array.max())
print(array.sum())

1
6
21


In [99]:
array = np.array([[1,2],[3,4],[5,6]])
array.sum(axis=1)

array([ 3,  7, 11])

In [100]:
array = np.array([[1,2],[3,4],[5,6]])
array.sum(axis=0)

array([ 9, 12])

In [101]:
array = np.array([[1,2],[3,4],[5,6]])
np.sqrt(array)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [103]:
array = np.array([[1,2],[3,4],[5,6]])
np.std(array)

1.707825127659933

In [107]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [108]:
#dot product of a matrix
a.dot(b)

array([[19, 22],
       [43, 50]])

In [113]:
print(a)
a[1,1]

[[1 2]
 [3 4]]


4

In [111]:
listt = [1,2,3,4,5]
listt[0:2]

[1, 2]

In [121]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
a[0:3,1]

array([2, 5, 8])

In [124]:
a[-1,0:1]

array([7])

In [128]:
# a[0:3,1:3]
a[ :, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [131]:
for element in a:
    print(element)

[1 2 3]
[4 5 6]
[7 8 9]


In [132]:
for element in a.flat:
    print(element)

1
2
3
4
5
6
7
8
9


In [133]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [134]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [135]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [136]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [137]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [151]:
np.stack((a,b), axis = 1)

array([[[ 0,  1],
        [ 6,  7]],

       [[ 2,  3],
        [ 8,  9]],

       [[ 4,  5],
        [10, 11]]])

In [150]:
np.stack((a,b), axis = 0)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [139]:
d1_a = np.arange(5)
d1_b = np.arange(5,10)

In [141]:
d1_a

array([0, 1, 2, 3, 4])

In [140]:
d1_b

array([5, 6, 7, 8, 9])

In [142]:
np.vstack((d1_a, d1_b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [146]:
np.stack((d1_a,d1_b), axis = 1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [147]:
np.stack((d1_a,d1_b), axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [149]:
np.hstack((d1_a, d1_b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
n_array = np.arange(30).reshape(2,15)
n_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [160]:
stored = np.hsplit(n_array,3)
for row in stored:
    print(row)

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [161]:
stored = np.vsplit(n_array,2)
for row in stored:
    print(row)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [165]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
a[2:,2:]

array([[10, 11]])

In [171]:
b = a >= 6
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [172]:
a[b]

array([ 6,  7,  8,  9, 10, 11])

In [175]:
a = np.arange(1, 13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [176]:
for row in a:
    for cell in row:
        print(cell)

1
2
3
4
5
6
7
8
9
10
11
12


In [180]:
# for cell in a.flatten():
#     print(cell)

for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9
10
11
12


In [181]:
for cell in a.flatten():
    print(cell)

1
2
3
4
5
6
7
8
9
10
11
12


In [191]:
for x in np.nditer(a, order = 'C'):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [192]:
for x in np.nditer(a, order = 'F', flags = ['external_loop']):
    print(x)

[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]


In [193]:
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = x*x
a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [194]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [196]:
for x,y in np.nditer([a,b]):
    print(y,x)

3 1
3 4
3 9
3 16
7 25
7 36
7 49
7 64
11 81
11 100
11 121
11 144
